const results = {
  "body": [
    {
      "id": 1,
      "language_family": "Northwest Caucasian",
      "name": "Abkhazian",
      "target_name": "Абхаз тілі",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ab",
      "iso_639_2t": "abk",
      "iso_639_2b": "abk",
      "iso_639_3": "abk",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 2,
      "language_family": "Afro-Asiatic",
      "name": "Afar",
      "target_name": "Qafár af",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "aa",
      "iso_639_2t": "aar",
      "iso_639_2b": "aar",
      "iso_639_3": "aar",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 3,
      "language_family": "Afro-Asiatic",
      "name": "Afar",
      "target_name": "ዓፋር",
      "dialect": null,
      "script_type": "Ge'ez",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "aag",
      "iso_639_2t": "aarg",
      "iso_639_2b": "aarg",
      "iso_639_3": "aarg",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 4,
      "language_family": "Afro-Asiatic",
      "name": "Afar",
      "target_name": "عف",
      "dialect": null,
      "script_type": "Arabic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "aaa",
      "iso_639_2t": "aara",
      "iso_639_2b": "aara",
      "iso_639_3": "aara",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 5,
      "language_family": "Indo-European",
      "name": "Afrikaans",
      "target_name": "Afrikaans",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "af",
      "iso_639_2t": "afr",
      "iso_639_2b": "afr",
      "iso_639_3": "afr",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 6,
      "language_family": "Niger–Congo",
      "name": "Akan",
      "target_name": "Akan",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ak",
      "iso_639_2t": "aka",
      "iso_639_2b": "aka",
      "iso_639_3": "aka2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 7,
      "language_family": "Indo-European",
      "name": "Albanian",
      "target_name": "shqiptar",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sq",
      "iso_639_2t": "sqi",
      "iso_639_2b": "alb",
      "iso_639_3": "sqi4",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 8,
      "language_family": "Afro-Asiatic",
      "name": "Amharic",
      "target_name": "አማርኛ",
      "dialect": null,
      "script_type": "Ge'ez",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "am",
      "iso_639_2t": "amh",
      "iso_639_2b": "amh",
      "iso_639_3": "amh",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 9,
      "language_family": "Afro-Asiatic",
      "name": "Arabic",
      "target_name": "عربى",
      "dialect": null,
      "script_type": "Arabic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ar",
      "iso_639_2t": "ara",
      "iso_639_2b": "ara",
      "iso_639_3": "ara30",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 10,
      "language_family": "Indo-European",
      "name": "Aragonese",
      "target_name": "Aragonés",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "an",
      "iso_639_2t": "arg",
      "iso_639_2b": "arg",
      "iso_639_3": "arg",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 11,
      "language_family": "Indo-European",
      "name": "Armenian",
      "target_name": "Հայերեն",
      "dialect": null,
      "script_type": "Armenian",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "hy",
      "iso_639_2t": "hye",
      "iso_639_2b": "arm",
      "iso_639_3": "hye",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 12,
      "language_family": "Indo-European",
      "name": "Assamese",
      "target_name": "অসমীয়া",
      "dialect": null,
      "script_type": "Assamese",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "as",
      "iso_639_2t": "asm",
      "iso_639_2b": "asm",
      "iso_639_3": "asm",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 13,
      "language_family": "Northeast Caucasian",
      "name": "Avaric",
      "target_name": "Магӏарул мацӏ / Авар мацӏ",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "av",
      "iso_639_2t": "ava",
      "iso_639_2b": "ava",
      "iso_639_3": "ava",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 14,
      "language_family": "Indo-European",
      "name": "Avestan",
      "target_name": "𐬛𐬍𐬥 𐬛𐬀𐬠𐬌𐬫𐬭𐬵",
      "dialect": null,
      "script_type": "Arabic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ae",
      "iso_639_2t": "ave",
      "iso_639_2b": "ave",
      "iso_639_3": "ave",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 15,
      "language_family": "Aymaran",
      "name": "Aymara",
      "target_name": "aymar aru",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ay",
      "iso_639_2t": "aym",
      "iso_639_2b": "aym",
      "iso_639_3": "aym2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 16,
      "language_family": "Turkic",
      "name": "Azerbaijani",
      "target_name": "Azərbaycan dili",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "az",
      "iso_639_2t": "aze",
      "iso_639_2b": "aze",
      "iso_639_3": "aze2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 17,
      "language_family": "Niger–Congo",
      "name": "Bambara",
      "target_name": "Bamanankan",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "bml",
      "iso_639_2t": "baml",
      "iso_639_2b": "baml",
      "iso_639_3": "baml",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 18,
      "language_family": "Turkic",
      "name": "Bashkir",
      "target_name": "Башҡорт теле, Başqort tele",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ba",
      "iso_639_2t": "bak",
      "iso_639_2b": "bak",
      "iso_639_3": "bak",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 19,
      "language_family": "Language isolate",
      "name": "Basque",
      "target_name": "Euskara",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "eu",
      "iso_639_2t": "eus",
      "iso_639_2b": "baq",
      "iso_639_3": "eus",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 20,
      "language_family": "Indo-European",
      "name": "Belarusian",
      "target_name": "Беларуская мова",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "be",
      "iso_639_2t": "bel",
      "iso_639_2b": "bel",
      "iso_639_3": "bel",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 21,
      "language_family": "Indo-European",
      "name": "Bengali",
      "target_name": "বাংলা",
      "dialect": null,
      "script_type": "Bengali",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "bn",
      "iso_639_2t": "ben",
      "iso_639_2b": "ben",
      "iso_639_3": "ben",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 22,
      "language_family": "Indo-European",
      "name": "Bhojpuri",
      "target_name": "भोजपुरी",
      "dialect": null,
      "script_type": "Nagari",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "bho",
      "iso_639_2t": "bho",
      "iso_639_2b": "bho",
      "iso_639_3": "bho",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 23,
      "language_family": "Creole",
      "name": "Bislama",
      "target_name": "Bislama",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "bi",
      "iso_639_2t": "bis",
      "iso_639_2b": "bis",
      "iso_639_3": "bis",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 24,
      "language_family": "Indo-European",
      "name": "Bosnian",
      "target_name": "bosanski",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "bs",
      "iso_639_2t": "bos",
      "iso_639_2b": "bos",
      "iso_639_3": "bos",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 25,
      "language_family": "Indo-European",
      "name": "Bosnian",
      "target_name": "босански",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "bs",
      "iso_639_2t": "bos",
      "iso_639_2b": "bos",
      "iso_639_3": "bos",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 26,
      "language_family": "Indo-European",
      "name": "Breton",
      "target_name": "Brezhoneg",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "br",
      "iso_639_2t": "bre",
      "iso_639_2b": "bre",
      "iso_639_3": "bre",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 27,
      "language_family": "Indo-European",
      "name": "Bulgarian",
      "target_name": "Български",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "bg",
      "iso_639_2t": "bul",
      "iso_639_2b": "bul",
      "iso_639_3": "bul",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 28,
      "language_family": "Sino-Tibetan",
      "name": "Burmese",
      "target_name": "မြန်မာစာ",
      "dialect": null,
      "script_type": "Burmese alphabet",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "my",
      "iso_639_2t": "mya",
      "iso_639_2b": "bur",
      "iso_639_3": "mya",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 29,
      "language_family": "Indo-European",
      "name": "Catalan",
      "target_name": "català",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ca",
      "iso_639_2t": "cat",
      "iso_639_2b": "cat",
      "iso_639_3": "cat",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 30,
      "language_family": "Austroasiatic",
      "name": "Central Khmer",
      "target_name": "ភាសាខ្មែរ",
      "dialect": null,
      "script_type": "Khmer",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "km",
      "iso_639_2t": "khm",
      "iso_639_2b": "khm",
      "iso_639_3": "khm",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 31,
      "language_family": "Austronesian",
      "name": "Chamorro",
      "target_name": "chamoru",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ch",
      "iso_639_2t": "cha",
      "iso_639_2b": "cha",
      "iso_639_3": "cha",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 32,
      "language_family": "Northeast Caucasian",
      "name": "Chechen",
      "target_name": "Нохчийн мотт",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ce",
      "iso_639_2t": "che",
      "iso_639_2b": "che",
      "iso_639_3": "che",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 33,
      "language_family": "Niger–Congo",
      "name": "Chichewa, Chewa, Nyanja",
      "target_name": "Chicheŵa",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ny",
      "iso_639_2t": "nya",
      "iso_639_2b": "nya",
      "iso_639_3": "nya",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 37,
      "language_family": "Indo-European",
      "name": "Church Slavic",
      "target_name": "Црькъвьнословѣньскъ ѩзыкъ",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "cu",
      "iso_639_2t": "chu",
      "iso_639_2b": "chu",
      "iso_639_3": "chu",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 38,
      "language_family": "Turkic",
      "name": "Chuvash",
      "target_name": "Чӑваш чӗлхи",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "cv",
      "iso_639_2t": "chv",
      "iso_639_2b": "chv",
      "iso_639_3": "chv",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 39,
      "language_family": "Indo-European",
      "name": "Cornish",
      "target_name": "Kernewek",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "kw",
      "iso_639_2t": "cor",
      "iso_639_2b": "cor",
      "iso_639_3": "cor",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 40,
      "language_family": "Indo-European",
      "name": "Corsican",
      "target_name": "corsu",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "co",
      "iso_639_2t": "cos",
      "iso_639_2b": "cos",
      "iso_639_3": "cos",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 41,
      "language_family": "Algonquian",
      "name": "Cree",
      "target_name": "Nēhiyawēwin",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "cr",
      "iso_639_2t": "cre",
      "iso_639_2b": "cre",
      "iso_639_3": "cre6",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 42,
      "language_family": "Algonquian",
      "name": "Cree",
      "target_name": "ᓀᐦᐃᔭᐍᐏᐣ",
      "dialect": null,
      "script_type": "Syllabics",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "crs",
      "iso_639_2t": "cres",
      "iso_639_2b": "cres",
      "iso_639_3": "cre6s",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 43,
      "language_family": "Indo-European",
      "name": "Croatian",
      "target_name": "hrvatski",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "hr",
      "iso_639_2t": "hrv",
      "iso_639_2b": "hrv",
      "iso_639_3": "hrv",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 44,
      "language_family": "Indo-European",
      "name": "Czech",
      "target_name": "český jazyk",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "cs",
      "iso_639_2t": "ces",
      "iso_639_2b": "cze",
      "iso_639_3": "ces",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 45,
      "language_family": "Indo-European",
      "name": "Danish",
      "target_name": "dansk",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "da",
      "iso_639_2t": "dan",
      "iso_639_2b": "dan",
      "iso_639_3": "dan",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 46,
      "language_family": "Indo-European",
      "name": "Dutch",
      "target_name": "Nederlands",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "nl",
      "iso_639_2t": "nld",
      "iso_639_2b": "dut",
      "iso_639_3": "nld",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 47,
      "language_family": "Sino-Tibetan",
      "name": "Dzongkha",
      "target_name": "རྫོང་ཁ",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "dz",
      "iso_639_2t": "dzo",
      "iso_639_2b": "dzo",
      "iso_639_3": "dzo",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 48,
      "language_family": "Indo-European",
      "name": "English",
      "target_name": "English",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "en",
      "iso_639_2t": "eng",
      "iso_639_2b": "eng",
      "iso_639_3": "eng",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 49,
      "language_family": "Constructed",
      "name": "Esperanto",
      "target_name": "Esperanto",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "eo",
      "iso_639_2t": "epo",
      "iso_639_2b": "epo",
      "iso_639_3": "epo",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 50,
      "language_family": "Niger–Congo",
      "name": "Ewe",
      "target_name": "Eʋegbe",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ee",
      "iso_639_2t": "ewe",
      "iso_639_2b": "ewe",
      "iso_639_3": "ewe",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 51,
      "language_family": "Indo-European",
      "name": "Faroese",
      "target_name": "føroyskt mál",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "fo",
      "iso_639_2t": "fao",
      "iso_639_2b": "fao",
      "iso_639_3": "fao",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 52,
      "language_family": "Austronesian",
      "name": "Fijian",
      "target_name": "Na vosa vaka-Viti",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "fj",
      "iso_639_2t": "fij",
      "iso_639_2b": "fij",
      "iso_639_3": "fij",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 53,
      "language_family": "Uralic",
      "name": "Finnish",
      "target_name": "suomen kieli",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "fi",
      "iso_639_2t": "fin",
      "iso_639_2b": "fin",
      "iso_639_3": "fin",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 54,
      "language_family": "Indo-European",
      "name": "Flemish",
      "target_name": "Vlaams",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "nlf",
      "iso_639_2t": "nldf",
      "iso_639_2b": "dutf",
      "iso_639_3": "nldf",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 55,
      "language_family": "Indo-European",
      "name": "French",
      "target_name": "français",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "fr",
      "iso_639_2t": "fra",
      "iso_639_2b": "fre",
      "iso_639_3": "fra",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 56,
      "language_family": "Niger–Congo",
      "name": "Fulah",
      "target_name": "Fulani",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ff",
      "iso_639_2t": "ful",
      "iso_639_2b": "ful",
      "iso_639_3": "ful9",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 57,
      "language_family": "Niger–Congo",
      "name": "Fulah",
      "target_name": "الفولاني",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ffa",
      "iso_639_2t": "fula",
      "iso_639_2b": "fula",
      "iso_639_3": "ful9a",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 58,
      "language_family": "Indo-European",
      "name": "Galician",
      "target_name": "Galego",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "gl",
      "iso_639_2t": "glg",
      "iso_639_2b": "glg",
      "iso_639_3": "glg",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 59,
      "language_family": "Niger–Congo",
      "name": "Ganda",
      "target_name": "Oluganda",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "lg",
      "iso_639_2t": "lug",
      "iso_639_2b": "lug",
      "iso_639_3": "lug",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 60,
      "language_family": "Kartvelian",
      "name": "Georgian",
      "target_name": "ქართული ენა",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ka",
      "iso_639_2t": "kat",
      "iso_639_2b": "geo",
      "iso_639_3": "kat",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 61,
      "language_family": "Indo-European",
      "name": "German",
      "target_name": "Deutsch",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "de",
      "iso_639_2t": "deu",
      "iso_639_2b": "ger",
      "iso_639_3": "deu",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 62,
      "language_family": "Indo-European",
      "name": "Greek, Modern",
      "target_name": "ελληνικά",
      "dialect": null,
      "script_type": "Greek",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "el",
      "iso_639_2t": "ell",
      "iso_639_2b": "gre",
      "iso_639_3": "ell",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 63,
      "language_family": "Indo-European",
      "name": "Greek, Ancient",
      "target_name": "Ἑλληνική",
      "dialect": null,
      "script_type": "Greek",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "grc",
      "iso_639_2t": "grc",
      "iso_639_2b": "grc",
      "iso_639_3": "grc",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 64,
      "language_family": "Tupian",
      "name": "Guarani",
      "target_name": "Avañe’ẽ",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "gn",
      "iso_639_2t": "grn",
      "iso_639_2b": "grn",
      "iso_639_3": "grn5",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 65,
      "language_family": "Indo-European",
      "name": "Gujarati",
      "target_name": "ગુજરાતી",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "gu",
      "iso_639_2t": "guj",
      "iso_639_2b": "guj",
      "iso_639_3": "guj",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 66,
      "language_family": "Creole",
      "name": "Haitian Creole",
      "target_name": "Kreyòl ayisyen",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ht",
      "iso_639_2t": "hat",
      "iso_639_2b": "hat",
      "iso_639_3": "hat",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 67,
      "language_family": "Afro-Asiatic",
      "name": "Hausa",
      "target_name": "Harshen",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ha",
      "iso_639_2t": "hau",
      "iso_639_2b": "hau",
      "iso_639_3": "hau",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 68,
      "language_family": "Afro-Asiatic",
      "name": "Hebrew",
      "target_name": "עִברִית",
      "dialect": null,
      "script_type": "Hebrew",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "he",
      "iso_639_2t": "heb",
      "iso_639_2b": "heb",
      "iso_639_3": "heb",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 69,
      "language_family": "Niger–Congo",
      "name": "Herero",
      "target_name": "Otjiherero",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "hz",
      "iso_639_2t": "her",
      "iso_639_2b": "her",
      "iso_639_3": "her",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 70,
      "language_family": "Indo-European",
      "name": "Hindi",
      "target_name": "हिन्दी",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "hi",
      "iso_639_2t": "hin",
      "iso_639_2b": "hin",
      "iso_639_3": "hin",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 71,
      "language_family": "Austronesian",
      "name": "Hiri Motu",
      "target_name": "Hiri Motu",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ho",
      "iso_639_2t": "hmo",
      "iso_639_2b": "hmo",
      "iso_639_3": "hmo",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 72,
      "language_family": "Uralic",
      "name": "Hungarian",
      "target_name": "magyar nyelv",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "hu",
      "iso_639_2t": "hun",
      "iso_639_2b": "hun",
      "iso_639_3": "hun",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 73,
      "language_family": "Indo-European",
      "name": "Icelandic",
      "target_name": "Íslenska",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "is",
      "iso_639_2t": "isl",
      "iso_639_2b": "ice",
      "iso_639_3": "isl",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 74,
      "language_family": "Constructed",
      "name": "Ido",
      "target_name": "Ido",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "io",
      "iso_639_2t": "ido",
      "iso_639_2b": "ido",
      "iso_639_3": "ido",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 75,
      "language_family": "Niger–Congo",
      "name": "Igbo",
      "target_name": "Ásụ̀sụ̀ Ìgbò",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ig",
      "iso_639_2t": "ibo",
      "iso_639_2b": "ibo",
      "iso_639_3": "ibo",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 76,
      "language_family": "Austronesian",
      "name": "Indonesian",
      "target_name": "Bahasa Indonesia",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "id",
      "iso_639_2t": "ind",
      "iso_639_2b": "ind",
      "iso_639_3": "ind",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 77,
      "language_family": "Eskimo–Aleut",
      "name": "Inuktitut",
      "target_name": "ᐃᓄᒃᑎᑐᑦ",
      "dialect": null,
      "script_type": "Syllabics",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "iu",
      "iso_639_2t": "iku",
      "iso_639_2b": "iku",
      "iso_639_3": "iku2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 78,
      "language_family": "Eskimo–Aleut",
      "name": "Inupiaq",
      "target_name": "Inupiatun",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ik",
      "iso_639_2t": "ipk",
      "iso_639_2b": "ipk",
      "iso_639_3": "ipk2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 79,
      "language_family": "Indo-European",
      "name": "Irish",
      "target_name": "Gaeilge",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ga",
      "iso_639_2t": "gle",
      "iso_639_2b": "gle",
      "iso_639_3": "gle",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 80,
      "language_family": "Indo-European",
      "name": "Italian",
      "target_name": "Italiano",
      "dialect": null,
      "script_type": "",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "it",
      "iso_639_2t": "ita",
      "iso_639_2b": "ita",
      "iso_639_3": "ita",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 82,
      "language_family": "Austronesian",
      "name": "Javanese",
      "target_name": "Basa Jawa",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "jv",
      "iso_639_2t": "jav",
      "iso_639_2b": "jav",
      "iso_639_3": "jav",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 83,
      "language_family": "Austronesian",
      "name": "Javanese",
      "target_name": "ꦧꦱ ꦗꦮ",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "jv",
      "iso_639_2t": "jav",
      "iso_639_2b": "jav",
      "iso_639_3": "jav",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 84,
      "language_family": "Eskimo–Aleut",
      "name": "Greenlandic",
      "target_name": "Kalaallisut",
      "dialect": null,
      "script_type": "",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "kl",
      "iso_639_2t": "kal",
      "iso_639_2b": "kal",
      "iso_639_3": "kal",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 85,
      "language_family": "Dravidian",
      "name": "Kannada",
      "target_name": "ಕನ್ನಡ",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "kn",
      "iso_639_2t": "kan",
      "iso_639_2b": "kan",
      "iso_639_3": "kan",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 86,
      "language_family": "Nilo-Saharan",
      "name": "Kanuri",
      "target_name": "Kanuri",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "kr",
      "iso_639_2t": "kau",
      "iso_639_2b": "kau",
      "iso_639_3": "kau3",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 87,
      "language_family": "Indo-European",
      "name": "Kashmiri",
      "target_name": "कॉशुर, كٲشُر",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ks",
      "iso_639_2t": "kas",
      "iso_639_2b": "kas",
      "iso_639_3": "kas",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 88,
      "language_family": "Turkic",
      "name": "Kazakh",
      "target_name": "Қазақ тілі",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "kk",
      "iso_639_2t": "kaz",
      "iso_639_2b": "kaz",
      "iso_639_3": "kaz",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 89,
      "language_family": "Niger–Congo",
      "name": "Kikuyu",
      "target_name": "Gĩkũyũ",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ki",
      "iso_639_2t": "kik",
      "iso_639_2b": "kik",
      "iso_639_3": "kik",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 90,
      "language_family": "Niger–Congo",
      "name": "Kinyarwanda",
      "target_name": "Ikinyarwanda",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "rw",
      "iso_639_2t": "kin",
      "iso_639_2b": "kin",
      "iso_639_3": "kin",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 91,
      "language_family": "Turkic",
      "name": "Kyrgyz",
      "target_name": "Кыргыз тили",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ky",
      "iso_639_2t": "kir",
      "iso_639_2b": "kir",
      "iso_639_3": "kir",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 92,
      "language_family": "Uralic",
      "name": "Komi",
      "target_name": "Коми кыв",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "kv",
      "iso_639_2t": "kom",
      "iso_639_2b": "kom",
      "iso_639_3": "kom2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 93,
      "language_family": "Niger–Congo",
      "name": "Kongo",
      "target_name": "Kikongo",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "kg",
      "iso_639_2t": "kon",
      "iso_639_2b": "kon",
      "iso_639_3": "kon3",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 94,
      "language_family": "Koreanic",
      "name": "Korean, South",
      "target_name": "한국어",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ko",
      "iso_639_2t": "kor",
      "iso_639_2b": "kor",
      "iso_639_3": "kor",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 95,
      "language_family": "Koreanic",
      "name": "Korean, North",
      "target_name": "조선말",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ko",
      "iso_639_2t": "kor",
      "iso_639_2b": "kor",
      "iso_639_3": "kor",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 96,
      "language_family": "Niger–Congo",
      "name": "Kwanyama",
      "target_name": "Kuanyama",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "kj",
      "iso_639_2t": "kua",
      "iso_639_2b": "kua",
      "iso_639_3": "kua",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 97,
      "language_family": "Indo-European",
      "name": "Kurdish",
      "target_name": "Kurdî",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ku",
      "iso_639_2t": "kur",
      "iso_639_2b": "kur",
      "iso_639_3": "kur3",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 98,
      "language_family": "Tai–Kadai",
      "name": "Lao",
      "target_name": "ພາສາລາວ",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "lo",
      "iso_639_2t": "lao",
      "iso_639_2b": "lao",
      "iso_639_3": "lao",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 99,
      "language_family": "Indo-European",
      "name": "Latin",
      "target_name": "Lingua Latina",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "la",
      "iso_639_2t": "lat",
      "iso_639_2b": "lat",
      "iso_639_3": "lat",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 100,
      "language_family": "Indo-European",
      "name": "Latvian",
      "target_name": "latviešu valoda",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "lv",
      "iso_639_2t": "lav",
      "iso_639_2b": "lav",
      "iso_639_3": "lav +2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 101,
      "language_family": "Indo-European",
      "name": "Limburgan, Limburger",
      "target_name": "lim",
      "dialect": null,
      "script_type": "Limburgish",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": " Limburgish",
      "iso_639_2t": "li",
      "iso_639_2b": "lim",
      "iso_639_3": "lim",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 102,
      "language_family": "Niger–Congo",
      "name": "Lingala",
      "target_name": "Ngala",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ln",
      "iso_639_2t": "lin",
      "iso_639_2b": "lin",
      "iso_639_3": "lin",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 103,
      "language_family": "Indo-European",
      "name": "Lithuanian",
      "target_name": "lietuvių kalba",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "lt",
      "iso_639_2t": "lit",
      "iso_639_2b": "lit",
      "iso_639_3": "lit",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 104,
      "language_family": "Niger–Congo",
      "name": "Luba-Katanga",
      "target_name": "Kiluba",
      "dialect": null,
      "script_type": "",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "lu",
      "iso_639_2t": "lub",
      "iso_639_2b": "lub",
      "iso_639_3": "lub",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 105,
      "language_family": "Indo-European",
      "name": "Luxembourgish",
      "target_name": "Lëtzebuergesch",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "lb",
      "iso_639_2t": "ltz",
      "iso_639_2b": "ltz",
      "iso_639_3": "ltz",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 106,
      "language_family": "Indo-European",
      "name": "Macedonian",
      "target_name": "македонски",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mk",
      "iso_639_2t": "mkd",
      "iso_639_2b": "mac",
      "iso_639_3": "mkd",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 107,
      "language_family": "Indo-European",
      "name": "Magahi",
      "target_name": "मगही",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mag",
      "iso_639_2t": "mag",
      "iso_639_2b": "mag",
      "iso_639_3": "mag",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 108,
      "language_family": "Austronesian",
      "name": "Malagasy",
      "target_name": "Fiteny Malagasy",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mg",
      "iso_639_2t": "mlg",
      "iso_639_2b": "mlg",
      "iso_639_3": "mlg11",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 109,
      "language_family": "Austronesian",
      "name": "Malay",
      "target_name": "بهاس ملايو",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ms",
      "iso_639_2t": "msa",
      "iso_639_2b": "may",
      "iso_639_3": "msa36",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 110,
      "language_family": "Dravidian",
      "name": "Malayalam",
      "target_name": "മലയാളം",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ml",
      "iso_639_2t": "mal",
      "iso_639_2b": "mal",
      "iso_639_3": "mal",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 111,
      "language_family": "Indo-European",
      "name": "Maldivian",
      "target_name": "ދިވެހި",
      "dialect": null,
      "script_type": "Thaana",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "dv",
      "iso_639_2t": "div",
      "iso_639_2b": "div",
      "iso_639_3": "div",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 112,
      "language_family": "Afro-Asiatic",
      "name": "Maltese",
      "target_name": "Malti",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mt",
      "iso_639_2t": "mlt",
      "iso_639_2b": "mlt",
      "iso_639_3": "mlt",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 113,
      "language_family": "Indo-European",
      "name": "Manx",
      "target_name": "Gaelg",
      "dialect": null,
      "script_type": "",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "gv",
      "iso_639_2t": "glv",
      "iso_639_2b": "glv",
      "iso_639_3": "glv",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 114,
      "language_family": "Austronesian",
      "name": "Maori",
      "target_name": "Te Reo Māori",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mi",
      "iso_639_2t": "mri",
      "iso_639_2b": "mao",
      "iso_639_3": "mri",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 115,
      "language_family": "Indo-European",
      "name": "Marathi",
      "target_name": "मराठी",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mr",
      "iso_639_2t": "mar",
      "iso_639_2b": "mar",
      "iso_639_3": "mar",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 116,
      "language_family": "Austronesian",
      "name": "Marshallese",
      "target_name": "Kajin M̧ajeļ",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mh",
      "iso_639_2t": "mah",
      "iso_639_2b": "mah",
      "iso_639_3": "mah",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 117,
      "language_family": "Mongolic",
      "name": "Mongolian",
      "target_name": "ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mn",
      "iso_639_2t": "mon",
      "iso_639_2b": "mon",
      "iso_639_3": "mon2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 118,
      "language_family": "Mongolic",
      "name": "Mongolian",
      "target_name": "монгол хэл",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "mnc",
      "iso_639_2t": "monc",
      "iso_639_2b": "monc",
      "iso_639_3": "mon2c",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 119,
      "language_family": "Austronesian",
      "name": "Nauruan",
      "target_name": "Nauru",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "na",
      "iso_639_2t": "nau",
      "iso_639_2b": "nau",
      "iso_639_3": "nau",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 120,
      "language_family": "Dené–Yeniseian",
      "name": "Navajo",
      "target_name": "Diné Bizaad",
      "dialect": null,
      "script_type": "Spoken",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "nv",
      "iso_639_2t": "nav",
      "iso_639_2b": "nav",
      "iso_639_3": "nav",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 121,
      "language_family": "Niger–Congo",
      "name": "Ndonga",
      "target_name": "Oshindonga",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ng",
      "iso_639_2t": "ndo",
      "iso_639_2b": "ndo",
      "iso_639_3": "ndo",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 122,
      "language_family": "Indo-European",
      "name": "Nepali",
      "target_name": "नेपाली",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ne",
      "iso_639_2t": "nep",
      "iso_639_2b": "nep",
      "iso_639_3": "nep2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 123,
      "language_family": "Niger–Congo",
      "name": "North Ndebele",
      "target_name": "Matabele",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "nd",
      "iso_639_2t": "nde",
      "iso_639_2b": "nde",
      "iso_639_3": "nde",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 124,
      "language_family": "Uralic",
      "name": "Northern Sami",
      "target_name": "davvisámegiella",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "se",
      "iso_639_2t": "sme",
      "iso_639_2b": "sme",
      "iso_639_3": "sme",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 125,
      "language_family": "Indo-European",
      "name": "Norwegian",
      "target_name": "norsk",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "no",
      "iso_639_2t": "nor",
      "iso_639_2b": "nor",
      "iso_639_3": "nor2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 126,
      "language_family": "Indo-European",
      "name": "Norwegian Bokmål",
      "target_name": "Bokmål",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "nb",
      "iso_639_2t": "nob",
      "iso_639_2b": "nob",
      "iso_639_3": "nob",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 127,
      "language_family": "Indo-European",
      "name": "Modern Norwegian",
      "target_name": "Nynorsk",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "nn",
      "iso_639_2t": "nno",
      "iso_639_2b": "nno",
      "iso_639_3": "nno",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 128,
      "language_family": "Indo-European",
      "name": "Occitan",
      "target_name": "lenga d'òc",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "oc",
      "iso_639_2t": "oci",
      "iso_639_2b": "oci",
      "iso_639_3": "oci",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 129,
      "language_family": "Algonquian",
      "name": "Ojibwa",
      "target_name": "Ojibwe",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "oj",
      "iso_639_2t": "oji",
      "iso_639_2b": "oji",
      "iso_639_3": "oji7",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 130,
      "language_family": "Algonquian",
      "name": "Ojibwa",
      "target_name": "ᐊᓂᐦᔑᓈᐯᒧᐎᓐ",
      "dialect": null,
      "script_type": "Symbol",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ojs",
      "iso_639_2t": "ojis",
      "iso_639_2b": "ojis",
      "iso_639_3": "oji7s",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 131,
      "language_family": "Indo-European",
      "name": "Odia",
      "target_name": "ଓଡ଼ିଆ",
      "dialect": null,
      "script_type": "Symbol",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "or",
      "iso_639_2t": "ori",
      "iso_639_2b": "ori",
      "iso_639_3": "ori2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 132,
      "language_family": "Afro-Asiatic",
      "name": "Oromo",
      "target_name": "Afaan Oromo",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "om",
      "iso_639_2t": "orm",
      "iso_639_2b": "orm",
      "iso_639_3": "orm4",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 133,
      "language_family": "Indo-European",
      "name": "Ossetian",
      "target_name": "ирон ӕвзаг",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "os",
      "iso_639_2t": "oss",
      "iso_639_2b": "oss",
      "iso_639_3": "oss",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 134,
      "language_family": "Indo-European",
      "name": "Pali",
      "target_name": "पालि",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "pi",
      "iso_639_2t": "pli",
      "iso_639_2b": "pli",
      "iso_639_3": "pli",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 135,
      "language_family": "Indo-European",
      "name": "Pashto",
      "target_name": "پښتو",
      "dialect": null,
      "script_type": "Arabic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ps",
      "iso_639_2t": "pus",
      "iso_639_2b": "pus",
      "iso_639_3": "pus",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 136,
      "language_family": "Indo-European",
      "name": "Persian (Farsi)",
      "target_name": "فارسی",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "fa",
      "iso_639_2t": "fas",
      "iso_639_2b": "per",
      "iso_639_3": "fas2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 137,
      "language_family": "Indo-European",
      "name": "Polish",
      "target_name": "polski",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "pl",
      "iso_639_2t": "pol",
      "iso_639_2b": "pol",
      "iso_639_3": "pol",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 138,
      "language_family": "Indo-European",
      "name": "Portuguese",
      "target_name": "Português",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "pt",
      "iso_639_2t": "por",
      "iso_639_2b": "por",
      "iso_639_3": "por",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 139,
      "language_family": "Indo-European",
      "name": "Punjabi, Panjabi",
      "target_name": "ਪੰਜਾਬੀ",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "pa",
      "iso_639_2t": "pan",
      "iso_639_2b": "pan",
      "iso_639_3": "pan",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 140,
      "language_family": "Quechuan",
      "name": "Quechua",
      "target_name": "Runa Simi",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "qu",
      "iso_639_2t": "que",
      "iso_639_2b": "que",
      "iso_639_3": "que43",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 141,
      "language_family": "Indo-European",
      "name": "Moldovan, Romanian",
      "target_name": "лимба молдовеняскэ",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ro",
      "iso_639_2t": "ron",
      "iso_639_2b": "rum",
      "iso_639_3": "ron",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 142,
      "language_family": "Indo-European",
      "name": "Romansh",
      "target_name": "Rumantsch",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "rm",
      "iso_639_2t": "roh",
      "iso_639_2b": "roh",
      "iso_639_3": "roh",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 143,
      "language_family": "Niger–Congo",
      "name": "Kirundi",
      "target_name": "íkiRǔndi",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "rn",
      "iso_639_2t": "run",
      "iso_639_2b": "run",
      "iso_639_3": "run",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 144,
      "language_family": "Indo-European",
      "name": "Russian",
      "target_name": "Русский язык",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ru",
      "iso_639_2t": "rus",
      "iso_639_2b": "rus",
      "iso_639_3": "rus",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 145,
      "language_family": "Austronesian",
      "name": "Samoan",
      "target_name": "Gagana fa‘a Sāmoa",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sm",
      "iso_639_2t": "smo",
      "iso_639_2b": "smo",
      "iso_639_3": "smo",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 146,
      "language_family": "Creole",
      "name": "Sango",
      "target_name": "yângâ tî sängö",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sg",
      "iso_639_2t": "sag",
      "iso_639_2b": "sag",
      "iso_639_3": "sag",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 147,
      "language_family": "Indo-European",
      "name": "Sanskrit",
      "target_name": "संस्कृतम्",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sa",
      "iso_639_2t": "san",
      "iso_639_2b": "san",
      "iso_639_3": "san",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 148,
      "language_family": "Indo-European",
      "name": "Sardinian",
      "target_name": "sardu",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sc",
      "iso_639_2t": "srd",
      "iso_639_2b": "srd",
      "iso_639_3": "srd4",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 149,
      "language_family": "Indo-European",
      "name": "Scottish Gaelic",
      "target_name": "Gàidhlig",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "gd",
      "iso_639_2t": "gla",
      "iso_639_2b": "gla",
      "iso_639_3": "gla",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 150,
      "language_family": "Indo-European",
      "name": "Serbian",
      "target_name": "српски",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sr",
      "iso_639_2t": "srp",
      "iso_639_2b": "srp",
      "iso_639_3": "srp",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 151,
      "language_family": "Niger–Congo",
      "name": "Shona",
      "target_name": "chiShona",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sn",
      "iso_639_2t": "sna",
      "iso_639_2b": "sna",
      "iso_639_3": "sna",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 153,
      "language_family": "Indo-European",
      "name": "Sindhi",
      "target_name": "سنڌي",
      "dialect": null,
      "script_type": "Arabic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sd",
      "iso_639_2t": "snd",
      "iso_639_2b": "snd",
      "iso_639_3": "snd",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 154,
      "language_family": "Indo-European",
      "name": "Sinhala",
      "target_name": "සිංහල",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "si",
      "iso_639_2t": "sin",
      "iso_639_2b": "sin",
      "iso_639_3": "sin",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 155,
      "language_family": "Indo-European",
      "name": "Slovak",
      "target_name": "Slovenčina",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sk",
      "iso_639_2t": "slk",
      "iso_639_2b": "slo",
      "iso_639_3": "slk",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 156,
      "language_family": "Indo-European",
      "name": "Slovenian",
      "target_name": "slovenski jezik",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sl",
      "iso_639_2t": "slv",
      "iso_639_2b": "slv",
      "iso_639_3": "slv",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 157,
      "language_family": "Afro-Asiatic",
      "name": "Somali",
      "target_name": "af Soomaali",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "so",
      "iso_639_2t": "som",
      "iso_639_2b": "som",
      "iso_639_3": "som",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 158,
      "language_family": "Niger–Congo",
      "name": "South Ndebele",
      "target_name": "isiNdebele",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "nr",
      "iso_639_2t": "nbl",
      "iso_639_2b": "nbl",
      "iso_639_3": "nbl",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 159,
      "language_family": "Niger–Congo",
      "name": "Southern Sotho",
      "target_name": "seSotho",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "st",
      "iso_639_2t": "sot",
      "iso_639_2b": "sot",
      "iso_639_3": "sot",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 160,
      "language_family": "Indo-European",
      "name": "Spanish, Castilian",
      "target_name": "",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "es",
      "iso_639_2t": "spa",
      "iso_639_2b": "spa",
      "iso_639_3": "spa",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 161,
      "language_family": "Austronesian",
      "name": "Sundanese",
      "target_name": "Basa Sunda",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "su",
      "iso_639_2t": "sun",
      "iso_639_2b": "sun",
      "iso_639_3": "sun",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 162,
      "language_family": "Niger–Congo",
      "name": "Swahili",
      "target_name": "kiSwahili",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sw",
      "iso_639_2t": "swa",
      "iso_639_2b": "swa",
      "iso_639_3": "swa2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 163,
      "language_family": "Niger–Congo",
      "name": "Swati",
      "target_name": "siSwati",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ss",
      "iso_639_2t": "ssw",
      "iso_639_2b": "ssw",
      "iso_639_3": "ssw",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 164,
      "language_family": "Indo-European",
      "name": "Swedish",
      "target_name": "svenska",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "sv",
      "iso_639_2t": "swe",
      "iso_639_2b": "swe",
      "iso_639_3": "swe",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 165,
      "language_family": "Austronesian",
      "name": "Tagalog",
      "target_name": "",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "tl",
      "iso_639_2t": "tgl",
      "iso_639_2b": "tgl",
      "iso_639_3": "tgl",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 166,
      "language_family": "Austronesian",
      "name": "Tahitian",
      "target_name": "Reo Tahiti",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ty",
      "iso_639_2t": "tah",
      "iso_639_2b": "tah",
      "iso_639_3": "tah",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 167,
      "language_family": "Indo-European",
      "name": "Tajik",
      "target_name": "тоҷикӣ",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "tg",
      "iso_639_2t": "tgk",
      "iso_639_2b": "tgk",
      "iso_639_3": "tgk",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 168,
      "language_family": "Dravidian",
      "name": "Tamil",
      "target_name": "தமிழ்",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ta",
      "iso_639_2t": "tam",
      "iso_639_2b": "tam",
      "iso_639_3": "tam",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 169,
      "language_family": "Turkic",
      "name": "Tatar",
      "target_name": "tatarça",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "tt",
      "iso_639_2t": "tat",
      "iso_639_2b": "tat",
      "iso_639_3": "tat",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 170,
      "language_family": "Dravidian",
      "name": "Telugu",
      "target_name": "తెలుగు",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "te",
      "iso_639_2t": "tel",
      "iso_639_2b": "tel",
      "iso_639_3": "tel",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 171,
      "language_family": "Tai–Kadai",
      "name": "Thai",
      "target_name": "ภาษาไทย",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "th",
      "iso_639_2t": "tha",
      "iso_639_2b": "tha",
      "iso_639_3": "tha",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 172,
      "language_family": "Sino-Tibetan",
      "name": "Tibetan",
      "target_name": "བོད་སྐད",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "bo",
      "iso_639_2t": "bod",
      "iso_639_2b": "tib",
      "iso_639_3": "bod",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 173,
      "language_family": "Afro-Asiatic",
      "name": "Tigrinya",
      "target_name": "ትግርኛ",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ti",
      "iso_639_2t": "tir",
      "iso_639_2b": "tir",
      "iso_639_3": "tir",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 174,
      "language_family": "Austronesian",
      "name": "Tonga(Tonga Islands)",
      "target_name": "Faka-Tonga",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "to",
      "iso_639_2t": "ton",
      "iso_639_2b": "ton",
      "iso_639_3": "ton",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 175,
      "language_family": "Niger–Congo",
      "name": "Tsonga",
      "target_name": "Xitsonga",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ts",
      "iso_639_2t": "tso",
      "iso_639_2b": "tso",
      "iso_639_3": "tso",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 176,
      "language_family": "Niger–Congo",
      "name": "Tswana",
      "target_name": "Setswana",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "tn",
      "iso_639_2t": "tsn",
      "iso_639_2b": "tsn",
      "iso_639_3": "tsn",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 177,
      "language_family": "Turkic",
      "name": "Turkish",
      "target_name": "Türkçe",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "tr",
      "iso_639_2t": "tur",
      "iso_639_2b": "tur",
      "iso_639_3": "tur",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 178,
      "language_family": "Turkic",
      "name": "Turkmen",
      "target_name": "Türkmen dili",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "tk",
      "iso_639_2t": "tuk",
      "iso_639_2b": "tuk",
      "iso_639_3": "tuk",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 179,
      "language_family": "Niger–Congo",
      "name": "Twi",
      "target_name": "Akan kasa",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "tw",
      "iso_639_2t": "twi",
      "iso_639_2b": "twi",
      "iso_639_3": "twi",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 180,
      "language_family": "Turkic",
      "name": "Uyghur",
      "target_name": "Уйғур",
      "dialect": null,
      "script_type": "Script",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ug",
      "iso_639_2t": "uig",
      "iso_639_2b": "uig",
      "iso_639_3": "uig",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 181,
      "language_family": "Indo-European",
      "name": "Ukrainian",
      "target_name": "українська мова",
      "dialect": null,
      "script_type": "Cyrillic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "uk",
      "iso_639_2t": "ukr",
      "iso_639_2b": "ukr",
      "iso_639_3": "ukr",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 182,
      "language_family": "Indo-European",
      "name": "Urdu",
      "target_name": "اُردُو",
      "dialect": null,
      "script_type": "Arabic",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ur",
      "iso_639_2t": "urd",
      "iso_639_2b": "urd",
      "iso_639_3": "urd",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 183,
      "language_family": "Turkic",
      "name": "Uzbek",
      "target_name": "Oʻzbekcha",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "uz",
      "iso_639_2t": "uzb",
      "iso_639_2b": "uzb",
      "iso_639_3": "uzb2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 184,
      "language_family": "Niger–Congo",
      "name": "Venda",
      "target_name": "Tshivenḓa",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "ve",
      "iso_639_2t": "ven",
      "iso_639_2b": "ven",
      "iso_639_3": "ven",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 185,
      "language_family": "Austroasiatic",
      "name": "Vietnamese",
      "target_name": "Tiếng Việt",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "vi",
      "iso_639_2t": "vie",
      "iso_639_2b": "vie",
      "iso_639_3": "vie",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 186,
      "language_family": "Constructed",
      "name": "Volapük",
      "target_name": "",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "vo",
      "iso_639_2t": "vol",
      "iso_639_2b": "vol",
      "iso_639_3": "vol",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 187,
      "language_family": "Indo-European",
      "name": "Walloon",
      "target_name": "walon",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "wa",
      "iso_639_2t": "wln",
      "iso_639_2b": "wln",
      "iso_639_3": "wln",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 188,
      "language_family": "Indo-European",
      "name": "Welsh",
      "target_name": "Cymraeg",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "cy",
      "iso_639_2t": "cym",
      "iso_639_2b": "wel",
      "iso_639_3": "cym",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 189,
      "language_family": "Indo-European",
      "name": "Western Frisian",
      "target_name": "Frysk",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "fy",
      "iso_639_2t": "fry",
      "iso_639_2b": "fry",
      "iso_639_3": "fry",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 190,
      "language_family": "Niger–Congo",
      "name": "Wolof",
      "target_name": "Wollof",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "wo",
      "iso_639_2t": "wol",
      "iso_639_2b": "wol",
      "iso_639_3": "wol",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 191,
      "language_family": "Niger–Congo",
      "name": "Xhosa",
      "target_name": "isiXhosa",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "xh",
      "iso_639_2t": "xho",
      "iso_639_2b": "xho",
      "iso_639_3": "xho",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 192,
      "language_family": "Indo-European",
      "name": "Yiddish",
      "target_name": "ייִדיש, יידיש",
      "dialect": null,
      "script_type": "Hebrew",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "yi",
      "iso_639_2t": "yid",
      "iso_639_2b": "yid",
      "iso_639_3": "yid2",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 193,
      "language_family": "Niger–Congo",
      "name": "Yoruba",
      "target_name": "Èdè Yorùbá",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "yo",
      "iso_639_2t": "yor",
      "iso_639_2b": "yor",
      "iso_639_3": "yor",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 194,
      "language_family": "Tai–Kadai",
      "name": "Old Zhuang",
      "target_name": "話僮",
      "dialect": null,
      "script_type": "Symbol",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "za",
      "iso_639_2t": "zha",
      "iso_639_2b": "zha",
      "iso_639_3": "zha +16",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 195,
      "language_family": "Tai–Kadai",
      "name": "New Zhuang",
      "target_name": "Vahcuengh",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "za",
      "iso_639_2t": "zha",
      "iso_639_2b": "zha",
      "iso_639_3": "zha +16",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 196,
      "language_family": "Niger–Congo",
      "name": "Zulu",
      "target_name": "isiZulu",
      "dialect": null,
      "script_type": "Latin",
      "has_romanization": false,
      "has_spaces_in_sentences": true,
      "iso_639_1": "zu",
      "iso_639_2t": "zul",
      "iso_639_2b": "zul",
      "iso_639_3": "zul",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 34,
      "language_family": "Sino-Tibetan",
      "name": "Chinese, Simplified",
      "target_name": "普通话",
      "dialect": null,
      "script_type": "Hanzi",
      "has_romanization": true,
      "has_spaces_in_sentences": false,
      "iso_639_1": "zh",
      "iso_639_2t": "zho",
      "iso_639_2b": "chi",
      "iso_639_3": "zh",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 35,
      "language_family": "Sino-Tibetan",
      "name": "Chinese, Traditional",
      "target_name": "普通話",
      "dialect": null,
      "script_type": "Hanzi",
      "has_romanization": true,
      "has_spaces_in_sentences": false,
      "iso_639_1": "hn",
      "iso_639_2t": "han",
      "iso_639_2b": "han",
      "iso_639_3": "han",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 36,
      "language_family": "Sino-Tibetan",
      "name": "Chinese, Cantonese",
      "target_name": "广东话",
      "dialect": null,
      "script_type": "Hanzi",
      "has_romanization": true,
      "has_spaces_in_sentences": false,
      "iso_639_1": "yu",
      "iso_639_2t": "yue",
      "iso_639_2b": "yue",
      "iso_639_3": "yue",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 81,
      "language_family": "Japonic",
      "name": "Japanese",
      "target_name": "日本語",
      "dialect": null,
      "script_type": "Kanji",
      "has_romanization": true,
      "has_spaces_in_sentences": false,
      "iso_639_1": "ja",
      "iso_639_2t": "jpn",
      "iso_639_2b": "jpn",
      "iso_639_3": "jpn",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    },
    {
      "id": 152,
      "language_family": "Sino-Tibetan",
      "name": "Sichuan Yi, Nuosu",
      "target_name": "彝语",
      "dialect": null,
      "script_type": "Hanzi",
      "has_romanization": true,
      "has_spaces_in_sentences": false,
      "iso_639_1": "ii",
      "iso_639_2t": "iii",
      "iso_639_2b": "iii",
      "iso_639_3": "iii",
      "created_at": "2022-01-03T00:13:09.016Z",
      "updated_at": null
    }
  ]
}